purge-logs.py: update to sf-infra version and do not try to remove symlink
2020-09-10 05:21:44,881 INFO  /var/www/logs/96/24796/12/check/rdoinfo-DLRN-check-centos8/c259e77/buildset/centos-rpm-master/repos/component/common/current : removing old logs
Traceback (most recent call last):
  File "/usr/local/bin/purge-logs.py", line 100, in <module>
    search_and_destroy(calculated_time, args.dry_run, root)
  File "/usr/local/bin/purge-logs.py", line 94, in search_and_destroy
    delete_dir(job_dir)
  File "/usr/local/bin/purge-logs.py", line 35, in delete_dir
    shutil.rmtree(dir_path)
  File "/usr/lib64/python3.6/shutil.py", line 496, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/lib64/python3.6/shutil.py", line 494, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link

Change-Id: Ib673b41d972ebbcc69e29f8124dd44d58f9340c9