Update patch set 17
Patch Set 17:

(2 comments)

I were unable to get the scheduler/merger get the zuul-jobs repo from gerrit.

When the scheduler starts I get in the merger log:
git.exc.GitCommandError: Cmd('git') failed due to: exit code(-13)
 cmdline: git clone -v ssh://zuul@managesf.sftests.com:29418/zuul-jobs  /var/opt/rh/rh-python35/lib/zuul/git/managesf.sftests.com/zuul-jobs

Using the regular git command under the zuul user it is ok the repo is fetched even with the closest env:
/usr/bin/scl enable rh-python35 -- git clone -v ssh://zuul@managesf.sftests.com:29418/zuul-jobs

Patch-set: 17