Update patch set 2
Patch Set 2:

I still have a concern about the cleaning of zuul-jobs. The patch populates base/config jobs/playbooks in the config repo but does not clean the previous ones into the zuul-jobs repository. So on my node after your patch have been deployed I still have in the job log (for a config-check) that line:  2017-11-15 16:23:11.359766 | PRE-RUN START: [trusted : managesf.sftests270.com/zuul-jobs/playbooks/base/pre@master] so It seems the zuul-jobs version is still used. On SF 2.6 when zuulv3 is deployed we have a zuul-jobs repo so an upgrade tasks to clean might be useful. I admit also this is a corner case situation as only sf-project.io have zuulv3 + sf 2.6.

According to the logs:
zuul.configloader.ConfigurationSyntaxError: Zuul encountered a syntax error while parsing its configuration in the
repo zuul-jobs on branch master.  The error was:

  Pipelines may not be defined in untrusted repos, they may only be
  defined in config repos.

That make sense.


So I tried to clean zuul-jobs via a review but zuul returned as gerrit comment that:

Zuul encountered a syntax error while parsing its configuration in the
repo demo-project-distgit on branch master.  The error was:

  Job base not defined

The error appears in the following job stanza:

  job:
      name: demo-rpmbuild
      parent: base
      description: Build the demo-project rpm
      run: build-rpm.yaml
      required-projects:
        - demo-project
        - demo-project-distgit

  in "demo-project-distgit/.zuul.yaml@master", line 2, column 3

Finally I direct pushed my change but it ends up in state I was unable to fix :( see the logs https://softwarefactory-project.io/paste/show/903/

Patch-set: 2